### PR TITLE
Handle case when id application env key is not set

### PR DESCRIPTION
**Pull request by kxepal**

### CODE REVIEW

**Comment by kxepal** [comment]
Need to note, that badmatch seems happens only for escript. `swirl:start()` in shell fetches version correctly.

**Comment by dch** [comment]
Thanks! `git bisect` says I broke it here 9f0df1b. I'd like to have the escript version print out correctly too, wonder what changed.

**Comment by dch** [comment]
Aha. It's because `swirl:start()` doesn't return successfully under escript. Digging further after a sunshine break.

```
=INFO REPORT==== 18-Jul-2015::16:44:00 ===
swirl: version #decf90c-dirty
escript: exception error: no match of right hand side value ok
  in function  swirl:main/1 (src/swirl.erl, line 230)
```

**Comment by dch** [comment]
Oops I changed the return code of `swirl:start()` for a simple `ok`. Here's a simpler fix:

```
%% for escript support
-spec main(any()) -> no_return().
main(_) ->
    ok = start(),
    {ok, _ } = start_peer(),
    timer:sleep(infinity).
```
The help text isnt useful anyway as there's no terminal support.

**Pull request closed without merging**
